name: Update WG Subscription

on:
  schedule:
    - cron: '0 0 * * *' # Раз в сутки
  workflow_dispatch: # Возможность запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests msgpack

      - name: Run converter
        run: python convert.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Проверяем, создался ли файл, и если нет - создаем пустой (чтобы не было ошибки)
          touch my_wg_sub.txt 
          git add my_wg_sub.txt
          # Фиксируем изменения, только если они есть
          git commit -m "Update subscription $(date)" || echo "No changes to commit"
          git push
